name: Sync site

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.gif'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.SITE_REPO_ACCESS_TOKEN }}
          repository: krABMaga/krABMaga.github.io
          event-type: updated
